### ISSUE TITLE
Implement GitHub Style Tags

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#306]
## what
* Use GitHub design for tags

![image](https://user-images.githubusercontent.com/52489/49778656-018e7f80-fcbb-11e8-89f0-acece320bd8d.png)

## references
* https://github.com/cloudposse/geodesic

## why
* This looks cleaner than our current strategy for displaying tags

**Comment by osterman** [comment]
To be clear, please make it look like this:

![image](https://user-images.githubusercontent.com/52489/50381075-21666180-0632-11e9-8453-d93945de230d.png)

Not like this:
![image](https://user-images.githubusercontent.com/52489/50381085-39d67c00-0632-11e9-9ad3-0514a6d9ab19.png)


## todo
- [ ] move tags below description at the top
- [ ] remove `#` hash symbol
- [ ] set top/bottom margin respectively
- [ ] ensure font-sizes is roughly the same as on github
